### ISSUE TITLE
Tanques

### ISSUE THREAD

**Issue by Lucky1661** [HeberonYT/skyfactory#1]
Buenas Heberon:
Cuando me crafteo el tanque del openblocks en el server de Skyblock se me crashea, porque puede ser?

**Comment by HeberonYT** [comment]
Hola!
Esto es normal debido a que el tanque del OpenBlocks esta desactivado en el server y no es crafteable.
Puedes usar otro tipo de tanques de otros mods.

**Comment by Lucky1661** [comment]
Pero por ejemplo para usar el sprinkler del openblocks es necesario tener un tanque con agua
