### ISSUE TITLE
crash report skyfactory 11 -05-2017

### ISSUE THREAD

**Issue by nube32** [HeberonYT/skyfactory#10]
Hola , no me deja entrar al servidor me aparece el mensaje siguiente: 

" Forge Mob Loader has found a problem with your minecraft installation ... The mods and versions listed below could not be found ... ThermalExpansion:any ... The file 'logs/fml-client-lates.log' contains more informacion "

 y el crash report esta detallado aqui: [https://pastebin.com/Bc2VVBUj](url) , por vafor copia y pega el link para que pueda ser visto ... gracias

**Comment by Buggui** [comment]
Problema solucionado.
