### ISSUE TITLE
Issue - Slime Sapling

### ISSUE THREAD

**Issue by Solmatic** [HeberonYT/skyfactory#12]
> _Slime sapling recipe does not work **NEI** shows a slime block in a sieve should work however the sieve does not accept the block_ (**Need Slime Leaves to Make Slime Leaf Fletching**)

_La receta de slime no trabaja **NEI** demuestra que un bloque de slime en el sieve debe trabajar sin embargo el sieve No acepta el bloque_ (**Necesito las hojas de slime para hacer Slime Leaf Fletching**) 

Gracias
@HeberonYT 

-Solmatic

**Comment by Solmatic** [comment]
@HeberonYT

**Comment by Buggui** [comment]
Se revisará si se puede solucionar.

**Comment by HeberonYT** [comment]
@Solmatic ya lo he revisado y todo parece funcionar bien, pero quizas sea que lo estas haciendo mal, mira aquí te explico.
El bloque de slime lo pones en el Sieve del Ex Nihilo, y alli lo intentas hasta que tengas la probabilidad de sacar la sapling, pero si lo haces en el Sieve del mod ExCompressum no funcionara y no dejará colocar el bloque de slime.
Aquí las fotos de ambos Sieves.
![screenshot_5](https://cloud.githubusercontent.com/assets/13698597/26135673/a99f5a58-3a7c-11e7-89e2-ac5b216abc37.png)
![screenshot_6](https://cloud.githubusercontent.com/assets/13698597/26135672/a99f9040-3a7c-11e7-8a2c-31ddf75b0143.png)

Por favor, menciona si esta resuelto tu problema.
Saludos!

**Comment by Solmatic** [comment]
Igual yo traté en ambos y si di con esa conclusión pero el único detalle es que el regular lo toma o se ve que lo toma pero te regresa el bloque pero ósea que solo hace la animación pero en realidad  no toma el bloque me lo regresa tengo un clip en el cual tengo 1 bloque de slime y el sieve simula como que lo toma pero me lo regresa a la mano y si le sigo dando es un loop en que dentra en el sieve según baja pero en eso me regresa el mismo bloque a la mano es muy raro disculpe si no me explico bien español es mi segundo idioma

**Comment by Solmatic** [comment]
@HeberonYT
https://twitter.com/solmatic714/status/864741202863603712
