### ISSUE TITLE
No se me cargaron las monedas del rango

### ISSUE THREAD

**Issue by mbedoya-dev** [HeberonYT/skyfactory#13]
Buenas noches, noté ayer que no tengo saldo, solamente tengo 10 monedas, nunca se me cargaron con el rango.
Reporte esto a los admin por el chat pero aun no sé si hay solución a esto.
Mi usuario es mauriyi rango TITAN
Gracias.

**Comment by HeberonYT** [comment]
Ya esta solucionado mauriyi, gracias Dianis!
