### ISSUE TITLE
Problemas de conxion

### ISSUE THREAD

**Issue by Yisus005** [HeberonYT/skyfactory#14]
Cuando ingreso al juego solo logro estar un rato en el servidor antes de que empieza a pausarse y me saca, luego trato de volver a entrar y se queda cargando y ya solo sale conexión perdida, tiempo de espera agotado.
Instale el mod pack actualizado y con el launcher viejo y nuevo pasa lo mismo.

**Comment by melohhh** [comment]
a mi me pasa lo mismo :( entro y no me puedo mover esta todo lag y me termina sacando, todo empezo hoy a la tarde :( nunca habia tenido problemas de conexion

fan;melohhh

**Comment by melohhh** [comment]
Que proveedor de Internet tenes Yisus005?

**Comment by melohhh** [comment]
Ya se arregló :)

**Comment by Yisus005** [comment]
Grax.
