### ISSUE TITLE
Crasheo con infusión del thaumcraft.

### ISSUE THREAD

**Issue by ghost** [HeberonYT/skyfactory#26]
Hoy intenté hacer el portal-in-a-box para poder ir a la dimensión del eldrich pero al hacerlo el servidor se reinicia y no me deja entrar hasta que alguien vaya a mi is y quite las cosas de la infusión pensé que era imposible hacer esta infusión pero Blackdemon97 logro hacerla.

**Comment by HeberonYT** [comment]
Podrías pedir información a ese usuario para saber en qué lugar realizó el ritual o en que nación lo hizo.
Posteriormente haré un mantenimiento a ese servidor para solucionar problemas y reportes acomunados.

Saludos!
