### ISSUE TITLE
chunk reseteado

### ISSUE THREAD

**Issue by melohhh** [HeberonYT/skyfactory#3]
hola heberon, hoy despues del reset de las 8 (arg) loguie y se me había reseteado un chunk por completo.
no entiendo nada, te mando un screenshot del drawer vacío e invisible (como ese hay 9 mas que no se ven y marca vacíos)
mi mana del botania completamente reseteado, estaba todo lleno. y algunas flores del botania se hicieron rojitas como las del minecraft vanilla.
todos los cofres que ves dentro del chunk se vaciaron.
perdí toda mi redstone , glowstone, ender perls, etc.... 
bueno no sé , :(  
chao y gracias por leer

![screenshot_3](https://cloud.githubusercontent.com/assets/24661589/25466212/60acfbc4-2add-11e7-9b85-9f099539874f.png)

![2017-04-26_20 39 36](https://cloud.githubusercontent.com/assets/24661589/25462164/b3af85e0-2ac3-11e7-8a9e-849fd17bfee1.png)

**Comment by Buggui** [comment]
Caso revisado.
