### ISSUE TITLE
Me robaron

### ISSUE THREAD

**Issue by AlSahHimRD** [HeberonYT/skyfactory#4]
sauerkraut1 mr robo un sieve normal y un heavy sieve y mi barrel y mi nodo de transmicion y la mejor de interaccion con sus cables ![2017-04-27_19 20 02](https://cloud.githubusercontent.com/assets/28121186/25508205/bc569954-2b6d-11e7-93bc-fcd6f4ed3291.png)
![2017-04-27_19 20 00](https://cloud.githubusercontent.com/assets/28121186/25508209/bf08db44-2b6d-11e7-93ed-1c50b763822d.png)
![2017-04-27_19 19 55](https://cloud.githubusercontent.com/assets/28121186/25508210/c0d14dbc-2b6d-11e7-94ed-705bd9c8ea7b.png)

**Comment by AlSahHimRD** [comment]
fue hace 10 minutos el 27 de abril de 2017

**Comment by Buggui** [comment]
Hola, por favor indica tu nombre de usuario de minecraft.

En las imágenes que adjuntas no se evidencia que el jugador que indicas te haya robado, tienes alguna otra prueba?

**Comment by Buggui** [comment]
Se revisó la isla no se encontró evidencia del jugador acusado. Tampoco se evidenció ningún robo solo explosiones de creeper.

Caso cerrado.
