### ISSUE TITLE
Staff of Traveling

### ISSUE THREAD

**Issue by melohhh** [HeberonYT/skyfactory#7]
Hola, vengo a reportar este item, ya que permite a los usuarios meterse a islas protegidas...
Como se ve en el video, Chaos entro a nuestra isla con el staff para avisarnos sobre el problema
(no estoy reportando al player, sino al item), Chaos nos hizo el favor de avisarnos.

Video: https://vimeo.com/215357116

**Comment by Buggui** [comment]
Gracias por reportar, ya estamos enterados del caso.  Se revisará el ítem.
