### ISSUE TITLE
Crasheo...

### ISSUE THREAD

**Issue by melohhh** [HeberonYT/skyfactory#9]
**Heberon, mi amigo Sessho entró ayer a una dimensión del RFTools y se le crasheo, y ya no lo deja logear, crashea ni bien entra
Help por favor :(**

![b9c37b8d7f5c4adb9dd42dd2889ec67c](https://cloud.githubusercontent.com/assets/24661589/25779400/428b3fa8-32ed-11e7-9b98-e9efdee6fd1b.png)

**Comment by HeberonYT** [comment]
Las dimensiones del RFTolls no están permitidas.
Se le ha colocado en el spawn principal, por favor avisarle al usuario que pruebe a entrar.

**Comment by melohhh** [comment]
Solucionado, muchas gracias :)!
